stages:
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: awcloud/facilityui:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/deployment-dev.yaml
        when:
          branch: master
          event: push
timeout: 360
notification: {}
